# Form implementation generated from reading ui file 'bookmark_import.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(574, 477)
        font = QtGui.QFont()
        font.setPointSize(11)
        Dialog.setFont(font)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.bookmark_path_entry = QtWidgets.QLineEdit(parent=Dialog)
        self.bookmark_path_entry.setObjectName("bookmark_path_entry")
        self.gridLayout.addWidget(self.bookmark_path_entry, 0, 1, 1, 1)
        self.bookmark_tree_widget = QtWidgets.QTreeWidget(parent=Dialog)
        self.bookmark_tree_widget.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.ExtendedSelection)
        self.bookmark_tree_widget.setColumnCount(3)
        self.bookmark_tree_widget.setObjectName("bookmark_tree_widget")
        self.gridLayout.addWidget(self.bookmark_tree_widget, 1, 0, 1, 3)
        self.browse_button = QtWidgets.QPushButton(parent=Dialog)
        self.browse_button.setObjectName("browse_button")
        self.gridLayout.addWidget(self.browse_button, 0, 2, 1, 1)
        self.bookmark_title_check_box = QtWidgets.QCheckBox(parent=Dialog)
        self.bookmark_title_check_box.setObjectName("bookmark_title_check_box")
        self.gridLayout.addWidget(self.bookmark_title_check_box, 3, 0, 1, 3)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Dialog)
        self.buttonBox.setToolTip("")
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 5, 0, 1, 3)
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.subfolder_check_box = QtWidgets.QCheckBox(parent=Dialog)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.subfolder_check_box.setFont(font)
        self.subfolder_check_box.setChecked(True)
        self.subfolder_check_box.setObjectName("subfolder_check_box")
        self.gridLayout.addWidget(self.subfolder_check_box, 2, 0, 1, 3)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Select bookmarks to import"))
        self.bookmark_path_entry.setToolTip(_translate("Dialog", "Firefox: places.sqlite in your firefox profile folder"))
        self.bookmark_tree_widget.headerItem().setText(0, _translate("Dialog", "Bookmark Title"))
        self.bookmark_tree_widget.headerItem().setText(1, _translate("Dialog", "Page Title"))
        self.bookmark_tree_widget.headerItem().setText(2, _translate("Dialog", "URL"))
        self.browse_button.setToolTip(_translate("Dialog", "Firefox: places.sqlite in your firefox profile folder"))
        self.browse_button.setText(_translate("Dialog", "Browse"))
        self.bookmark_title_check_box.setText(_translate("Dialog", "Use the bookmark title as URL title"))
        self.label.setToolTip(_translate("Dialog", "Firefox: places.sqlite in your firefox profile folder"))
        self.label.setText(_translate("Dialog", "Bookmarks file"))
        self.subfolder_check_box.setText(_translate("Dialog", "Import bookmarks of all subfolders of selected folders"))
