# Form implementation generated from reading ui file 'metadata_suggestions.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(988, 700)
        font = QtGui.QFont()
        font.setPointSize(11)
        Dialog.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.line = QtWidgets.QFrame(parent=Dialog)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.frame = QtWidgets.QFrame(parent=Dialog)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=self.frame)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Apply|QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 2, 0, 1, 6)
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.columns_table = QtWidgets.QTableView(parent=self.frame)
        self.columns_table.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.columns_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.columns_table.setObjectName("columns_table")
        self.columns_table.verticalHeader().setVisible(False)
        self.gridLayout.addWidget(self.columns_table, 1, 0, 1, 3)
        self.columns_add_button = QtWidgets.QToolButton(parent=self.frame)
        icon = QtGui.QIcon.fromTheme("list-add")
        self.columns_add_button.setIcon(icon)
        self.columns_add_button.setObjectName("columns_add_button")
        self.gridLayout.addWidget(self.columns_add_button, 0, 1, 1, 1)
        self.suggestions_remove_button = QtWidgets.QToolButton(parent=self.frame)
        icon = QtGui.QIcon.fromTheme("list-remove")
        self.suggestions_remove_button.setIcon(icon)
        self.suggestions_remove_button.setObjectName("suggestions_remove_button")
        self.gridLayout.addWidget(self.suggestions_remove_button, 0, 5, 1, 1)
        self.columns_remove_button = QtWidgets.QToolButton(parent=self.frame)
        icon = QtGui.QIcon.fromTheme("list-remove")
        self.columns_remove_button.setIcon(icon)
        self.columns_remove_button.setObjectName("columns_remove_button")
        self.gridLayout.addWidget(self.columns_remove_button, 0, 2, 1, 1)
        self.suggestions_add_button = QtWidgets.QToolButton(parent=self.frame)
        icon = QtGui.QIcon.fromTheme("list-add")
        self.suggestions_add_button.setIcon(icon)
        self.suggestions_add_button.setObjectName("suggestions_add_button")
        self.gridLayout.addWidget(self.suggestions_add_button, 0, 4, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.frame)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 3, 1, 1)
        self.suggestions_table = QtWidgets.QTableView(parent=self.frame)
        self.suggestions_table.setDragEnabled(True)
        self.suggestions_table.setDragDropMode(QtWidgets.QAbstractItemView.DragDropMode.InternalMove)
        self.suggestions_table.setDefaultDropAction(QtCore.Qt.DropAction.MoveAction)
        self.suggestions_table.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.suggestions_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.suggestions_table.setObjectName("suggestions_table")
        self.suggestions_table.verticalHeader().setVisible(False)
        self.gridLayout.addWidget(self.suggestions_table, 1, 3, 1, 3)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Edit metadata suggestions"))
        self.label.setText(_translate("Dialog", "Columns to generate suggestions for:"))
        self.columns_add_button.setText(_translate("Dialog", "..."))
        self.suggestions_remove_button.setText(_translate("Dialog", "..."))
        self.columns_remove_button.setText(_translate("Dialog", "..."))
        self.suggestions_add_button.setText(_translate("Dialog", "..."))
        self.label_2.setText(_translate("Dialog", "Suggestions for selected column:"))
