# Form implementation generated from reading ui file 'bookmark_import.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_Dialog:
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(605, 477)
        font = QtGui.QFont()
        font.setPointSize(11)
        Dialog.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(parent=Dialog)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.bookmark_title_check_box = QtWidgets.QCheckBox(parent=self.frame)
        self.bookmark_title_check_box.setObjectName("bookmark_title_check_box")
        self.gridLayout_2.addWidget(self.bookmark_title_check_box, 5, 0, 1, 4)
        self.subfolder_check_box = QtWidgets.QCheckBox(parent=self.frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.subfolder_check_box.setFont(font)
        self.subfolder_check_box.setChecked(True)
        self.subfolder_check_box.setObjectName("subfolder_check_box")
        self.gridLayout_2.addWidget(self.subfolder_check_box, 4, 0, 1, 4)
        self.bookmark_path_entry = QtWidgets.QLineEdit(parent=self.frame)
        self.bookmark_path_entry.setObjectName("bookmark_path_entry")
        self.gridLayout_2.addWidget(self.bookmark_path_entry, 0, 2, 1, 1)
        self.bookmark_tree_widget = QtWidgets.QTreeWidget(parent=self.frame)
        self.bookmark_tree_widget.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.ExtendedSelection)
        self.bookmark_tree_widget.setColumnCount(3)
        self.bookmark_tree_widget.setObjectName("bookmark_tree_widget")
        self.gridLayout_2.addWidget(self.bookmark_tree_widget, 2, 0, 2, 5)
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.WhatsThisCursor))
        self.label.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.browse_button = QtWidgets.QToolButton(parent=self.frame)
        self.browse_button.setObjectName("browse_button")
        self.gridLayout_2.addWidget(self.browse_button, 0, 3, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=self.frame)
        self.buttonBox.setToolTip("")
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_2.addWidget(self.buttonBox, 6, 0, 1, 5)
        self.verticalLayout.addWidget(self.frame)
        self.verticalLayout.setStretch(0, 1)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Select bookmarks to import"))
        self.bookmark_title_check_box.setText(_translate("Dialog", "Use the bookmark title as URL title"))
        self.subfolder_check_box.setText(_translate("Dialog", "Import bookmarks of all subfolders of selected folders"))
        self.bookmark_tree_widget.headerItem().setText(0, _translate("Dialog", "Bookmark Title"))
        self.bookmark_tree_widget.headerItem().setText(1, _translate("Dialog", "Page Title"))
        self.bookmark_tree_widget.headerItem().setText(2, _translate("Dialog", "URL"))
        self.label.setToolTip(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">The location of your bookmarks depends on your browser.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">For Firefox: &quot;places.sqlite&quot; in your firefox profile folder</span></p></body></html>"))
        self.label.setText(_translate("Dialog", "Bookmarks file"))
        self.browse_button.setText(_translate("Dialog", "..."))
